disabled_rules: # rule identifiers to exclude from running
    - cyclomatic_complexity
    - function_body_length
    - large_tuple
    - function_parameter_count
    - weak_delegate
    - notification_center_detachment
    - todo
    - class_delegate_protocol
    - identifier_name
opt_in_rules: # some rules are only opt-in
    - array_init
    - empty_count
    - force_unwrapping
    - force_cast
    - implicit_return
    - implicitly_unwrapped_optional
    - joined_default_parameter
    - literal_expression_end_indentation
    - modifier_order
    - multiline_function_chains
    - multiline_parameters
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - prefixed_toplevel_constant
    - private_action
    - private_outlet
    - trailing_closure
    - unneeded_break_in_switch
    - unneeded_parentheses_in_closure_argument
    - untyped_error_in_catch
    - unused_import
    - yoda_condition

# Find all the available rules by running:
# swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
- FlareApp
- FlareAppTests
- FlareAppUITests
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
    severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 110
# they can set both implicitly with an array
type_body_length:
    - 300 # warning
    - 400 # error
# or they can set both explicitly
file_length:
    warning: 500
    error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
    min_length: 4 # only warning
    max_length: # warning and error
        warning: 40
        error: 50
    excluded: iPhone # excluded via string
identifier_name:
    excluded:  # excluded via string array
        - !str id
        - i
    min_length: # only min_length
        warning: 1
    max_length:
        warning: 1000
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
